[scrolling]
# How many lines of scrollback to keep,
# '0' will disable scrolling.
history = 10000

# Number of lines the viewport will move for every line
# scrolled when scrollback is enabled (history > 0).
multiplier = 3

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

# Colors (Gruvbox Material Medium Dark)
# Default colors
[colors.primary]
background = '#282828'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
